source: src
paths:
  uploads: uploads
collections_config: {
  pages: {
    path: ''
  },
  data: {
    path: '_data'
  }
}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: America/Edmonton
