email: info@freestylemovement.ca
keywords: >-
  edmonton, breakdance, practice, session, bboy, bgirl, breakdancer, break,
  dance, hiphop, hip hop, yeg, choreography, freestyle, movement, art, culture
url: https://freestylemovement.ca


sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - bootstrap

exclude: 
  - "Gemfile"
  - "siteicon.png"
  - "Gemfile.lock"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"